/*
Copyright 2018 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/magicsong/s2iapiserver/pkg/apis/devops/v1alpha1"
	scheme "github.com/magicsong/s2iapiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RerunsGetter has a method to return a RerunInterface.
// A group's client should implement this interface.
type RerunsGetter interface {
	Reruns(namespace string) RerunInterface
}

// RerunInterface has methods to work with Rerun resources.
type RerunInterface interface {
	Create(*v1alpha1.Rerun) (*v1alpha1.Rerun, error)
	Update(*v1alpha1.Rerun) (*v1alpha1.Rerun, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Rerun, error)
	List(opts v1.ListOptions) (*v1alpha1.RerunList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Rerun, err error)
	RerunExpansion
}

// reruns implements RerunInterface
type reruns struct {
	client rest.Interface
	ns     string
}

// newReruns returns a Reruns
func newReruns(c *DevopsV1alpha1Client, namespace string) *reruns {
	return &reruns{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rerun, and returns the corresponding rerun object, and an error if there is any.
func (c *reruns) Get(name string, options v1.GetOptions) (result *v1alpha1.Rerun, err error) {
	result = &v1alpha1.Rerun{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reruns").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Reruns that match those selectors.
func (c *reruns) List(opts v1.ListOptions) (result *v1alpha1.RerunList, err error) {
	result = &v1alpha1.RerunList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested reruns.
func (c *reruns) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("reruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a rerun and creates it.  Returns the server's representation of the rerun, and an error, if there is any.
func (c *reruns) Create(rerun *v1alpha1.Rerun) (result *v1alpha1.Rerun, err error) {
	result = &v1alpha1.Rerun{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("reruns").
		Body(rerun).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rerun and updates it. Returns the server's representation of the rerun, and an error, if there is any.
func (c *reruns) Update(rerun *v1alpha1.Rerun) (result *v1alpha1.Rerun, err error) {
	result = &v1alpha1.Rerun{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("reruns").
		Name(rerun.Name).
		Body(rerun).
		Do().
		Into(result)
	return
}

// Delete takes name of the rerun and deletes it. Returns an error if one occurs.
func (c *reruns) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reruns").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *reruns) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reruns").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rerun.
func (c *reruns) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Rerun, err error) {
	result = &v1alpha1.Rerun{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("reruns").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
