// +build !ignore_autogenerated

/*
Copyright 2018 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	devops "github.com/magicsong/s2iapiserver/pkg/apis/devops"
	constants "github.com/magicsong/s2iapiserver/pkg/apis/devops/constants"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AuthConfig)(nil), (*devops.AuthConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthConfig_To_devops_AuthConfig(a.(*AuthConfig), b.(*devops.AuthConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.AuthConfig)(nil), (*AuthConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_AuthConfig_To_v1alpha1_AuthConfig(a.(*devops.AuthConfig), b.(*AuthConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CGroupLimits)(nil), (*devops.CGroupLimits)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CGroupLimits_To_devops_CGroupLimits(a.(*CGroupLimits), b.(*devops.CGroupLimits), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.CGroupLimits)(nil), (*CGroupLimits)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_CGroupLimits_To_v1alpha1_CGroupLimits(a.(*devops.CGroupLimits), b.(*CGroupLimits), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DockerConfig)(nil), (*devops.DockerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DockerConfig_To_devops_DockerConfig(a.(*DockerConfig), b.(*devops.DockerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.DockerConfig)(nil), (*DockerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_DockerConfig_To_v1alpha1_DockerConfig(a.(*devops.DockerConfig), b.(*DockerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnvironmentSpec)(nil), (*devops.EnvironmentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EnvironmentSpec_To_devops_EnvironmentSpec(a.(*EnvironmentSpec), b.(*devops.EnvironmentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.EnvironmentSpec)(nil), (*EnvironmentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_EnvironmentSpec_To_v1alpha1_EnvironmentSpec(a.(*devops.EnvironmentSpec), b.(*EnvironmentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Payload)(nil), (*devops.Payload)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Payload_To_devops_Payload(a.(*Payload), b.(*devops.Payload), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.Payload)(nil), (*Payload)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_Payload_To_v1alpha1_Payload(a.(*devops.Payload), b.(*Payload), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxyConfig)(nil), (*devops.ProxyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxyConfig_To_devops_ProxyConfig(a.(*ProxyConfig), b.(*devops.ProxyConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ProxyConfig)(nil), (*ProxyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ProxyConfig_To_v1alpha1_ProxyConfig(a.(*devops.ProxyConfig), b.(*ProxyConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Rerun)(nil), (*devops.Rerun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Rerun_To_devops_Rerun(a.(*Rerun), b.(*devops.Rerun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.Rerun)(nil), (*Rerun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_Rerun_To_v1alpha1_Rerun(a.(*devops.Rerun), b.(*Rerun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RerunList)(nil), (*devops.RerunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RerunList_To_devops_RerunList(a.(*RerunList), b.(*devops.RerunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.RerunList)(nil), (*RerunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_RerunList_To_v1alpha1_RerunList(a.(*devops.RerunList), b.(*RerunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2IRunResult)(nil), (*devops.S2IRunResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2IRunResult_To_devops_S2IRunResult(a.(*S2IRunResult), b.(*devops.S2IRunResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2IRunResult)(nil), (*S2IRunResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2IRunResult_To_v1alpha1_S2IRunResult(a.(*devops.S2IRunResult), b.(*S2IRunResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilder)(nil), (*devops.S2iBuilder)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilder_To_devops_S2iBuilder(a.(*S2iBuilder), b.(*devops.S2iBuilder), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilder)(nil), (*S2iBuilder)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilder_To_v1alpha1_S2iBuilder(a.(*devops.S2iBuilder), b.(*S2iBuilder), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderList)(nil), (*devops.S2iBuilderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList(a.(*S2iBuilderList), b.(*devops.S2iBuilderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderList)(nil), (*S2iBuilderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList(a.(*devops.S2iBuilderList), b.(*S2iBuilderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderSpec)(nil), (*devops.S2iBuilderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(a.(*S2iBuilderSpec), b.(*devops.S2iBuilderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderSpec)(nil), (*S2iBuilderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(a.(*devops.S2iBuilderSpec), b.(*S2iBuilderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderStatus)(nil), (*devops.S2iBuilderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(a.(*S2iBuilderStatus), b.(*devops.S2iBuilderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderStatus)(nil), (*S2iBuilderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(a.(*devops.S2iBuilderStatus), b.(*S2iBuilderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderStatusStrategy)(nil), (*devops.S2iBuilderStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy(a.(*S2iBuilderStatusStrategy), b.(*devops.S2iBuilderStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderStatusStrategy)(nil), (*S2iBuilderStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy(a.(*devops.S2iBuilderStatusStrategy), b.(*S2iBuilderStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderStrategy)(nil), (*devops.S2iBuilderStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy(a.(*S2iBuilderStrategy), b.(*devops.S2iBuilderStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderStrategy)(nil), (*S2iBuilderStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy(a.(*devops.S2iBuilderStrategy), b.(*S2iBuilderStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iConfig)(nil), (*devops.S2iConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iConfig_To_devops_S2iConfig(a.(*S2iConfig), b.(*devops.S2iConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iConfig)(nil), (*S2iConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iConfig_To_v1alpha1_S2iConfig(a.(*devops.S2iConfig), b.(*S2iConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRun)(nil), (*devops.S2iRun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRun_To_devops_S2iRun(a.(*S2iRun), b.(*devops.S2iRun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRun)(nil), (*S2iRun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRun_To_v1alpha1_S2iRun(a.(*devops.S2iRun), b.(*S2iRun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunList)(nil), (*devops.S2iRunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunList_To_devops_S2iRunList(a.(*S2iRunList), b.(*devops.S2iRunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunList)(nil), (*S2iRunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunList_To_v1alpha1_S2iRunList(a.(*devops.S2iRunList), b.(*S2iRunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunSpec)(nil), (*devops.S2iRunSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(a.(*S2iRunSpec), b.(*devops.S2iRunSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunSpec)(nil), (*S2iRunSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(a.(*devops.S2iRunSpec), b.(*S2iRunSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunStatus)(nil), (*devops.S2iRunStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(a.(*S2iRunStatus), b.(*devops.S2iRunStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunStatus)(nil), (*S2iRunStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(a.(*devops.S2iRunStatus), b.(*S2iRunStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunStatusStrategy)(nil), (*devops.S2iRunStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy(a.(*S2iRunStatusStrategy), b.(*devops.S2iRunStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunStatusStrategy)(nil), (*S2iRunStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy(a.(*devops.S2iRunStatusStrategy), b.(*S2iRunStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunStrategy)(nil), (*devops.S2iRunStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy(a.(*S2iRunStrategy), b.(*devops.S2iRunStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunStrategy)(nil), (*S2iRunStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy(a.(*devops.S2iRunStrategy), b.(*S2iRunStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Trigger)(nil), (*devops.Trigger)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Trigger_To_devops_Trigger(a.(*Trigger), b.(*devops.Trigger), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.Trigger)(nil), (*Trigger)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_Trigger_To_v1alpha1_Trigger(a.(*devops.Trigger), b.(*Trigger), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VolumeSpec)(nil), (*devops.VolumeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VolumeSpec_To_devops_VolumeSpec(a.(*VolumeSpec), b.(*devops.VolumeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.VolumeSpec)(nil), (*VolumeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_VolumeSpec_To_v1alpha1_VolumeSpec(a.(*devops.VolumeSpec), b.(*VolumeSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AuthConfig_To_devops_AuthConfig(in *AuthConfig, out *devops.AuthConfig, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	out.Email = in.Email
	out.ServerAddress = in.ServerAddress
	return nil
}

// Convert_v1alpha1_AuthConfig_To_devops_AuthConfig is an autogenerated conversion function.
func Convert_v1alpha1_AuthConfig_To_devops_AuthConfig(in *AuthConfig, out *devops.AuthConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthConfig_To_devops_AuthConfig(in, out, s)
}

func autoConvert_devops_AuthConfig_To_v1alpha1_AuthConfig(in *devops.AuthConfig, out *AuthConfig, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	out.Email = in.Email
	out.ServerAddress = in.ServerAddress
	return nil
}

// Convert_devops_AuthConfig_To_v1alpha1_AuthConfig is an autogenerated conversion function.
func Convert_devops_AuthConfig_To_v1alpha1_AuthConfig(in *devops.AuthConfig, out *AuthConfig, s conversion.Scope) error {
	return autoConvert_devops_AuthConfig_To_v1alpha1_AuthConfig(in, out, s)
}

func autoConvert_v1alpha1_CGroupLimits_To_devops_CGroupLimits(in *CGroupLimits, out *devops.CGroupLimits, s conversion.Scope) error {
	out.MemoryLimitBytes = in.MemoryLimitBytes
	out.CPUShares = in.CPUShares
	out.CPUPeriod = in.CPUPeriod
	out.CPUQuota = in.CPUQuota
	out.MemorySwap = in.MemorySwap
	out.Parent = in.Parent
	return nil
}

// Convert_v1alpha1_CGroupLimits_To_devops_CGroupLimits is an autogenerated conversion function.
func Convert_v1alpha1_CGroupLimits_To_devops_CGroupLimits(in *CGroupLimits, out *devops.CGroupLimits, s conversion.Scope) error {
	return autoConvert_v1alpha1_CGroupLimits_To_devops_CGroupLimits(in, out, s)
}

func autoConvert_devops_CGroupLimits_To_v1alpha1_CGroupLimits(in *devops.CGroupLimits, out *CGroupLimits, s conversion.Scope) error {
	out.MemoryLimitBytes = in.MemoryLimitBytes
	out.CPUShares = in.CPUShares
	out.CPUPeriod = in.CPUPeriod
	out.CPUQuota = in.CPUQuota
	out.MemorySwap = in.MemorySwap
	out.Parent = in.Parent
	return nil
}

// Convert_devops_CGroupLimits_To_v1alpha1_CGroupLimits is an autogenerated conversion function.
func Convert_devops_CGroupLimits_To_v1alpha1_CGroupLimits(in *devops.CGroupLimits, out *CGroupLimits, s conversion.Scope) error {
	return autoConvert_devops_CGroupLimits_To_v1alpha1_CGroupLimits(in, out, s)
}

func autoConvert_v1alpha1_DockerConfig_To_devops_DockerConfig(in *DockerConfig, out *devops.DockerConfig, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	out.CAFile = in.CAFile
	out.UseTLS = in.UseTLS
	out.TLSVerify = in.TLSVerify
	return nil
}

// Convert_v1alpha1_DockerConfig_To_devops_DockerConfig is an autogenerated conversion function.
func Convert_v1alpha1_DockerConfig_To_devops_DockerConfig(in *DockerConfig, out *devops.DockerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DockerConfig_To_devops_DockerConfig(in, out, s)
}

func autoConvert_devops_DockerConfig_To_v1alpha1_DockerConfig(in *devops.DockerConfig, out *DockerConfig, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	out.CAFile = in.CAFile
	out.UseTLS = in.UseTLS
	out.TLSVerify = in.TLSVerify
	return nil
}

// Convert_devops_DockerConfig_To_v1alpha1_DockerConfig is an autogenerated conversion function.
func Convert_devops_DockerConfig_To_v1alpha1_DockerConfig(in *devops.DockerConfig, out *DockerConfig, s conversion.Scope) error {
	return autoConvert_devops_DockerConfig_To_v1alpha1_DockerConfig(in, out, s)
}

func autoConvert_v1alpha1_EnvironmentSpec_To_devops_EnvironmentSpec(in *EnvironmentSpec, out *devops.EnvironmentSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_EnvironmentSpec_To_devops_EnvironmentSpec is an autogenerated conversion function.
func Convert_v1alpha1_EnvironmentSpec_To_devops_EnvironmentSpec(in *EnvironmentSpec, out *devops.EnvironmentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_EnvironmentSpec_To_devops_EnvironmentSpec(in, out, s)
}

func autoConvert_devops_EnvironmentSpec_To_v1alpha1_EnvironmentSpec(in *devops.EnvironmentSpec, out *EnvironmentSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_devops_EnvironmentSpec_To_v1alpha1_EnvironmentSpec is an autogenerated conversion function.
func Convert_devops_EnvironmentSpec_To_v1alpha1_EnvironmentSpec(in *devops.EnvironmentSpec, out *EnvironmentSpec, s conversion.Scope) error {
	return autoConvert_devops_EnvironmentSpec_To_v1alpha1_EnvironmentSpec(in, out, s)
}

func autoConvert_v1alpha1_Payload_To_devops_Payload(in *Payload, out *devops.Payload, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_Payload_To_devops_Payload is an autogenerated conversion function.
func Convert_v1alpha1_Payload_To_devops_Payload(in *Payload, out *devops.Payload, s conversion.Scope) error {
	return autoConvert_v1alpha1_Payload_To_devops_Payload(in, out, s)
}

func autoConvert_devops_Payload_To_v1alpha1_Payload(in *devops.Payload, out *Payload, s conversion.Scope) error {
	return nil
}

// Convert_devops_Payload_To_v1alpha1_Payload is an autogenerated conversion function.
func Convert_devops_Payload_To_v1alpha1_Payload(in *devops.Payload, out *Payload, s conversion.Scope) error {
	return autoConvert_devops_Payload_To_v1alpha1_Payload(in, out, s)
}

func autoConvert_v1alpha1_ProxyConfig_To_devops_ProxyConfig(in *ProxyConfig, out *devops.ProxyConfig, s conversion.Scope) error {
	out.HTTPProxy = in.HTTPProxy
	out.HTTPSProxy = in.HTTPSProxy
	return nil
}

// Convert_v1alpha1_ProxyConfig_To_devops_ProxyConfig is an autogenerated conversion function.
func Convert_v1alpha1_ProxyConfig_To_devops_ProxyConfig(in *ProxyConfig, out *devops.ProxyConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxyConfig_To_devops_ProxyConfig(in, out, s)
}

func autoConvert_devops_ProxyConfig_To_v1alpha1_ProxyConfig(in *devops.ProxyConfig, out *ProxyConfig, s conversion.Scope) error {
	out.HTTPProxy = in.HTTPProxy
	out.HTTPSProxy = in.HTTPSProxy
	return nil
}

// Convert_devops_ProxyConfig_To_v1alpha1_ProxyConfig is an autogenerated conversion function.
func Convert_devops_ProxyConfig_To_v1alpha1_ProxyConfig(in *devops.ProxyConfig, out *ProxyConfig, s conversion.Scope) error {
	return autoConvert_devops_ProxyConfig_To_v1alpha1_ProxyConfig(in, out, s)
}

func autoConvert_v1alpha1_Rerun_To_devops_Rerun(in *Rerun, out *devops.Rerun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1alpha1_Rerun_To_devops_Rerun is an autogenerated conversion function.
func Convert_v1alpha1_Rerun_To_devops_Rerun(in *Rerun, out *devops.Rerun, s conversion.Scope) error {
	return autoConvert_v1alpha1_Rerun_To_devops_Rerun(in, out, s)
}

func autoConvert_devops_Rerun_To_v1alpha1_Rerun(in *devops.Rerun, out *Rerun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_devops_Rerun_To_v1alpha1_Rerun is an autogenerated conversion function.
func Convert_devops_Rerun_To_v1alpha1_Rerun(in *devops.Rerun, out *Rerun, s conversion.Scope) error {
	return autoConvert_devops_Rerun_To_v1alpha1_Rerun(in, out, s)
}

func autoConvert_v1alpha1_RerunList_To_devops_RerunList(in *RerunList, out *devops.RerunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]devops.Rerun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RerunList_To_devops_RerunList is an autogenerated conversion function.
func Convert_v1alpha1_RerunList_To_devops_RerunList(in *RerunList, out *devops.RerunList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RerunList_To_devops_RerunList(in, out, s)
}

func autoConvert_devops_RerunList_To_v1alpha1_RerunList(in *devops.RerunList, out *RerunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Rerun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_devops_RerunList_To_v1alpha1_RerunList is an autogenerated conversion function.
func Convert_devops_RerunList_To_v1alpha1_RerunList(in *devops.RerunList, out *RerunList, s conversion.Scope) error {
	return autoConvert_devops_RerunList_To_v1alpha1_RerunList(in, out, s)
}

func autoConvert_v1alpha1_S2IRunResult_To_devops_S2IRunResult(in *S2IRunResult, out *devops.S2IRunResult, s conversion.Scope) error {
	out.ImageName = in.ImageName
	out.CompletionTime = (*v1.Time)(unsafe.Pointer(in.CompletionTime))
	out.Artifact = in.Artifact
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_S2IRunResult_To_devops_S2IRunResult is an autogenerated conversion function.
func Convert_v1alpha1_S2IRunResult_To_devops_S2IRunResult(in *S2IRunResult, out *devops.S2IRunResult, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2IRunResult_To_devops_S2IRunResult(in, out, s)
}

func autoConvert_devops_S2IRunResult_To_v1alpha1_S2IRunResult(in *devops.S2IRunResult, out *S2IRunResult, s conversion.Scope) error {
	out.ImageName = in.ImageName
	out.CompletionTime = (*v1.Time)(unsafe.Pointer(in.CompletionTime))
	out.Artifact = in.Artifact
	out.Message = in.Message
	return nil
}

// Convert_devops_S2IRunResult_To_v1alpha1_S2IRunResult is an autogenerated conversion function.
func Convert_devops_S2IRunResult_To_v1alpha1_S2IRunResult(in *devops.S2IRunResult, out *S2IRunResult, s conversion.Scope) error {
	return autoConvert_devops_S2IRunResult_To_v1alpha1_S2IRunResult(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilder_To_devops_S2iBuilder(in *S2iBuilder, out *devops.S2iBuilder, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_S2iBuilder_To_devops_S2iBuilder is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilder_To_devops_S2iBuilder(in *S2iBuilder, out *devops.S2iBuilder, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilder_To_devops_S2iBuilder(in, out, s)
}

func autoConvert_devops_S2iBuilder_To_v1alpha1_S2iBuilder(in *devops.S2iBuilder, out *S2iBuilder, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_S2iBuilder_To_v1alpha1_S2iBuilder is an autogenerated conversion function.
func Convert_devops_S2iBuilder_To_v1alpha1_S2iBuilder(in *devops.S2iBuilder, out *S2iBuilder, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilder_To_v1alpha1_S2iBuilder(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList(in *S2iBuilderList, out *devops.S2iBuilderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]devops.S2iBuilder)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList(in *S2iBuilderList, out *devops.S2iBuilderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList(in, out, s)
}

func autoConvert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList(in *devops.S2iBuilderList, out *S2iBuilderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]S2iBuilder)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList is an autogenerated conversion function.
func Convert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList(in *devops.S2iBuilderList, out *S2iBuilderList, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(in *S2iBuilderSpec, out *devops.S2iBuilderSpec, s conversion.Scope) error {
	out.Config = (*devops.S2iConfig)(unsafe.Pointer(in.Config))
	return nil
}

// Convert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(in *S2iBuilderSpec, out *devops.S2iBuilderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(in, out, s)
}

func autoConvert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(in *devops.S2iBuilderSpec, out *S2iBuilderSpec, s conversion.Scope) error {
	out.Config = (*S2iConfig)(unsafe.Pointer(in.Config))
	return nil
}

// Convert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec is an autogenerated conversion function.
func Convert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(in *devops.S2iBuilderSpec, out *S2iBuilderSpec, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(in *S2iBuilderStatus, out *devops.S2iBuilderStatus, s conversion.Scope) error {
	out.RunCount = in.RunCount
	out.LastRunState = constants.RunningState(in.LastRunState)
	out.LastRunName = (*string)(unsafe.Pointer(in.LastRunName))
	return nil
}

// Convert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(in *S2iBuilderStatus, out *devops.S2iBuilderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(in, out, s)
}

func autoConvert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(in *devops.S2iBuilderStatus, out *S2iBuilderStatus, s conversion.Scope) error {
	out.RunCount = in.RunCount
	out.LastRunState = constants.RunningState(in.LastRunState)
	out.LastRunName = (*string)(unsafe.Pointer(in.LastRunName))
	return nil
}

// Convert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus is an autogenerated conversion function.
func Convert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(in *devops.S2iBuilderStatus, out *S2iBuilderStatus, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy(in *S2iBuilderStatusStrategy, out *devops.S2iBuilderStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy(in *S2iBuilderStatusStrategy, out *devops.S2iBuilderStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy(in, out, s)
}

func autoConvert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy(in *devops.S2iBuilderStatusStrategy, out *S2iBuilderStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy is an autogenerated conversion function.
func Convert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy(in *devops.S2iBuilderStatusStrategy, out *S2iBuilderStatusStrategy, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy(in *S2iBuilderStrategy, out *devops.S2iBuilderStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy(in *S2iBuilderStrategy, out *devops.S2iBuilderStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy(in, out, s)
}

func autoConvert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy(in *devops.S2iBuilderStrategy, out *S2iBuilderStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy is an autogenerated conversion function.
func Convert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy(in *devops.S2iBuilderStrategy, out *S2iBuilderStrategy, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy(in, out, s)
}

func autoConvert_v1alpha1_S2iConfig_To_devops_S2iConfig(in *S2iConfig, out *devops.S2iConfig, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	out.BuilderImage = in.BuilderImage
	out.BuilderImageVersion = in.BuilderImageVersion
	out.BuilderBaseImageVersion = in.BuilderBaseImageVersion
	out.RuntimeImage = in.RuntimeImage
	out.OutputImageName = in.OutputImageName
	out.RuntimeImagePullPolicy = constants.PullPolicy(in.RuntimeImagePullPolicy)
	if err := Convert_v1alpha1_AuthConfig_To_devops_AuthConfig(&in.RuntimeAuthentication, &out.RuntimeAuthentication, s); err != nil {
		return err
	}
	out.RuntimeArtifacts = *(*[]devops.VolumeSpec)(unsafe.Pointer(&in.RuntimeArtifacts))
	out.DockerConfig = (*devops.DockerConfig)(unsafe.Pointer(in.DockerConfig))
	if err := Convert_v1alpha1_AuthConfig_To_devops_AuthConfig(&in.PullAuthentication, &out.PullAuthentication, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AuthConfig_To_devops_AuthConfig(&in.PushAuthentication, &out.PushAuthentication, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AuthConfig_To_devops_AuthConfig(&in.IncrementalAuthentication, &out.IncrementalAuthentication, s); err != nil {
		return err
	}
	out.DockerNetworkMode = constants.DockerNetworkMode(in.DockerNetworkMode)
	out.PreserveWorkingDir = in.PreserveWorkingDir
	out.IgnoreSubmodules = in.IgnoreSubmodules
	out.Tag = in.Tag
	out.BuilderPullPolicy = constants.PullPolicy(in.BuilderPullPolicy)
	out.PreviousImagePullPolicy = constants.PullPolicy(in.PreviousImagePullPolicy)
	out.Incremental = in.Incremental
	out.IncrementalFromTag = in.IncrementalFromTag
	out.RemovePreviousImage = in.RemovePreviousImage
	out.Environment = *(*[]devops.EnvironmentSpec)(unsafe.Pointer(&in.Environment))
	out.LabelNamespace = in.LabelNamespace
	out.CallbackURL = in.CallbackURL
	out.ScriptsURL = in.ScriptsURL
	out.Destination = in.Destination
	out.WorkingDir = in.WorkingDir
	out.WorkingSourceDir = in.WorkingSourceDir
	out.LayeredBuild = in.LayeredBuild
	out.Quiet = in.Quiet
	out.ForceCopy = in.ForceCopy
	out.ContextDir = in.ContextDir
	out.AssembleUser = in.AssembleUser
	out.RunImage = in.RunImage
	out.Usage = in.Usage
	out.Injections = *(*[]devops.VolumeSpec)(unsafe.Pointer(&in.Injections))
	out.CGroupLimits = (*devops.CGroupLimits)(unsafe.Pointer(in.CGroupLimits))
	out.DropCapabilities = *(*[]string)(unsafe.Pointer(&in.DropCapabilities))
	out.ScriptDownloadProxyConfig = (*devops.ProxyConfig)(unsafe.Pointer(in.ScriptDownloadProxyConfig))
	out.ExcludeRegExp = in.ExcludeRegExp
	out.BlockOnBuild = in.BlockOnBuild
	out.HasOnBuild = in.HasOnBuild
	out.BuildVolumes = *(*[]string)(unsafe.Pointer(&in.BuildVolumes))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.SecurityOpt = *(*[]string)(unsafe.Pointer(&in.SecurityOpt))
	out.KeepSymlinks = in.KeepSymlinks
	out.AsDockerfile = in.AsDockerfile
	out.ImageWorkDir = in.ImageWorkDir
	out.ImageScriptsURL = in.ImageScriptsURL
	out.AddHost = *(*[]string)(unsafe.Pointer(&in.AddHost))
	out.Export = in.Export
	out.SourceURL = in.SourceURL
	return nil
}

// Convert_v1alpha1_S2iConfig_To_devops_S2iConfig is an autogenerated conversion function.
func Convert_v1alpha1_S2iConfig_To_devops_S2iConfig(in *S2iConfig, out *devops.S2iConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iConfig_To_devops_S2iConfig(in, out, s)
}

func autoConvert_devops_S2iConfig_To_v1alpha1_S2iConfig(in *devops.S2iConfig, out *S2iConfig, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	out.BuilderImage = in.BuilderImage
	out.BuilderImageVersion = in.BuilderImageVersion
	out.BuilderBaseImageVersion = in.BuilderBaseImageVersion
	out.RuntimeImage = in.RuntimeImage
	out.OutputImageName = in.OutputImageName
	out.RuntimeImagePullPolicy = constants.PullPolicy(in.RuntimeImagePullPolicy)
	if err := Convert_devops_AuthConfig_To_v1alpha1_AuthConfig(&in.RuntimeAuthentication, &out.RuntimeAuthentication, s); err != nil {
		return err
	}
	out.RuntimeArtifacts = *(*[]VolumeSpec)(unsafe.Pointer(&in.RuntimeArtifacts))
	out.DockerConfig = (*DockerConfig)(unsafe.Pointer(in.DockerConfig))
	if err := Convert_devops_AuthConfig_To_v1alpha1_AuthConfig(&in.PullAuthentication, &out.PullAuthentication, s); err != nil {
		return err
	}
	if err := Convert_devops_AuthConfig_To_v1alpha1_AuthConfig(&in.PushAuthentication, &out.PushAuthentication, s); err != nil {
		return err
	}
	if err := Convert_devops_AuthConfig_To_v1alpha1_AuthConfig(&in.IncrementalAuthentication, &out.IncrementalAuthentication, s); err != nil {
		return err
	}
	out.DockerNetworkMode = constants.DockerNetworkMode(in.DockerNetworkMode)
	out.PreserveWorkingDir = in.PreserveWorkingDir
	out.IgnoreSubmodules = in.IgnoreSubmodules
	out.Tag = in.Tag
	out.BuilderPullPolicy = constants.PullPolicy(in.BuilderPullPolicy)
	out.PreviousImagePullPolicy = constants.PullPolicy(in.PreviousImagePullPolicy)
	out.Incremental = in.Incremental
	out.IncrementalFromTag = in.IncrementalFromTag
	out.RemovePreviousImage = in.RemovePreviousImage
	out.Environment = *(*[]EnvironmentSpec)(unsafe.Pointer(&in.Environment))
	out.LabelNamespace = in.LabelNamespace
	out.CallbackURL = in.CallbackURL
	out.ScriptsURL = in.ScriptsURL
	out.Destination = in.Destination
	out.WorkingDir = in.WorkingDir
	out.WorkingSourceDir = in.WorkingSourceDir
	out.LayeredBuild = in.LayeredBuild
	out.Quiet = in.Quiet
	out.ForceCopy = in.ForceCopy
	out.ContextDir = in.ContextDir
	out.AssembleUser = in.AssembleUser
	out.RunImage = in.RunImage
	out.Usage = in.Usage
	out.Injections = *(*[]VolumeSpec)(unsafe.Pointer(&in.Injections))
	out.CGroupLimits = (*CGroupLimits)(unsafe.Pointer(in.CGroupLimits))
	out.DropCapabilities = *(*[]string)(unsafe.Pointer(&in.DropCapabilities))
	out.ScriptDownloadProxyConfig = (*ProxyConfig)(unsafe.Pointer(in.ScriptDownloadProxyConfig))
	out.ExcludeRegExp = in.ExcludeRegExp
	out.BlockOnBuild = in.BlockOnBuild
	out.HasOnBuild = in.HasOnBuild
	out.BuildVolumes = *(*[]string)(unsafe.Pointer(&in.BuildVolumes))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.SecurityOpt = *(*[]string)(unsafe.Pointer(&in.SecurityOpt))
	out.KeepSymlinks = in.KeepSymlinks
	out.AsDockerfile = in.AsDockerfile
	out.ImageWorkDir = in.ImageWorkDir
	out.ImageScriptsURL = in.ImageScriptsURL
	out.AddHost = *(*[]string)(unsafe.Pointer(&in.AddHost))
	out.Export = in.Export
	out.SourceURL = in.SourceURL
	return nil
}

// Convert_devops_S2iConfig_To_v1alpha1_S2iConfig is an autogenerated conversion function.
func Convert_devops_S2iConfig_To_v1alpha1_S2iConfig(in *devops.S2iConfig, out *S2iConfig, s conversion.Scope) error {
	return autoConvert_devops_S2iConfig_To_v1alpha1_S2iConfig(in, out, s)
}

func autoConvert_v1alpha1_S2iRun_To_devops_S2iRun(in *S2iRun, out *devops.S2iRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_S2iRun_To_devops_S2iRun is an autogenerated conversion function.
func Convert_v1alpha1_S2iRun_To_devops_S2iRun(in *S2iRun, out *devops.S2iRun, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRun_To_devops_S2iRun(in, out, s)
}

func autoConvert_devops_S2iRun_To_v1alpha1_S2iRun(in *devops.S2iRun, out *S2iRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_S2iRun_To_v1alpha1_S2iRun is an autogenerated conversion function.
func Convert_devops_S2iRun_To_v1alpha1_S2iRun(in *devops.S2iRun, out *S2iRun, s conversion.Scope) error {
	return autoConvert_devops_S2iRun_To_v1alpha1_S2iRun(in, out, s)
}

func autoConvert_v1alpha1_S2iRunList_To_devops_S2iRunList(in *S2iRunList, out *devops.S2iRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]devops.S2iRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_S2iRunList_To_devops_S2iRunList is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunList_To_devops_S2iRunList(in *S2iRunList, out *devops.S2iRunList, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunList_To_devops_S2iRunList(in, out, s)
}

func autoConvert_devops_S2iRunList_To_v1alpha1_S2iRunList(in *devops.S2iRunList, out *S2iRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]S2iRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_devops_S2iRunList_To_v1alpha1_S2iRunList is an autogenerated conversion function.
func Convert_devops_S2iRunList_To_v1alpha1_S2iRunList(in *devops.S2iRunList, out *S2iRunList, s conversion.Scope) error {
	return autoConvert_devops_S2iRunList_To_v1alpha1_S2iRunList(in, out, s)
}

func autoConvert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(in *S2iRunSpec, out *devops.S2iRunSpec, s conversion.Scope) error {
	out.BuilderName = in.BuilderName
	out.BackoffLimit = in.BackoffLimit
	out.SecondsAfterFinished = in.SecondsAfterFinished
	out.Environment = *(*[]devops.EnvironmentSpec)(unsafe.Pointer(&in.Environment))
	out.OverideTag = in.OverideTag
	return nil
}

// Convert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(in *S2iRunSpec, out *devops.S2iRunSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(in, out, s)
}

func autoConvert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(in *devops.S2iRunSpec, out *S2iRunSpec, s conversion.Scope) error {
	out.BuilderName = in.BuilderName
	out.BackoffLimit = in.BackoffLimit
	out.SecondsAfterFinished = in.SecondsAfterFinished
	out.Environment = *(*[]EnvironmentSpec)(unsafe.Pointer(&in.Environment))
	out.OverideTag = in.OverideTag
	return nil
}

// Convert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec is an autogenerated conversion function.
func Convert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(in *devops.S2iRunSpec, out *S2iRunSpec, s conversion.Scope) error {
	return autoConvert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(in, out, s)
}

func autoConvert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(in *S2iRunStatus, out *devops.S2iRunStatus, s conversion.Scope) error {
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	out.RunState = constants.RunningState(in.RunState)
	out.Trigger = (*devops.Trigger)(unsafe.Pointer(in.Trigger))
	out.Result = (*devops.S2IRunResult)(unsafe.Pointer(in.Result))
	return nil
}

// Convert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(in *S2iRunStatus, out *devops.S2iRunStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(in, out, s)
}

func autoConvert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(in *devops.S2iRunStatus, out *S2iRunStatus, s conversion.Scope) error {
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	out.RunState = constants.RunningState(in.RunState)
	out.Trigger = (*Trigger)(unsafe.Pointer(in.Trigger))
	out.Result = (*S2IRunResult)(unsafe.Pointer(in.Result))
	return nil
}

// Convert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus is an autogenerated conversion function.
func Convert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(in *devops.S2iRunStatus, out *S2iRunStatus, s conversion.Scope) error {
	return autoConvert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(in, out, s)
}

func autoConvert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy(in *S2iRunStatusStrategy, out *devops.S2iRunStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy(in *S2iRunStatusStrategy, out *devops.S2iRunStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy(in, out, s)
}

func autoConvert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy(in *devops.S2iRunStatusStrategy, out *S2iRunStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy is an autogenerated conversion function.
func Convert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy(in *devops.S2iRunStatusStrategy, out *S2iRunStatusStrategy, s conversion.Scope) error {
	return autoConvert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy(in *S2iRunStrategy, out *devops.S2iRunStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy(in *S2iRunStrategy, out *devops.S2iRunStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy(in, out, s)
}

func autoConvert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy(in *devops.S2iRunStrategy, out *S2iRunStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy is an autogenerated conversion function.
func Convert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy(in *devops.S2iRunStrategy, out *S2iRunStrategy, s conversion.Scope) error {
	return autoConvert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy(in, out, s)
}

func autoConvert_v1alpha1_Trigger_To_devops_Trigger(in *Trigger, out *devops.Trigger, s conversion.Scope) error {
	out.Source = constants.TriggerSource(in.Source)
	out.Event = in.Event
	out.Payload = (*devops.Payload)(unsafe.Pointer(in.Payload))
	return nil
}

// Convert_v1alpha1_Trigger_To_devops_Trigger is an autogenerated conversion function.
func Convert_v1alpha1_Trigger_To_devops_Trigger(in *Trigger, out *devops.Trigger, s conversion.Scope) error {
	return autoConvert_v1alpha1_Trigger_To_devops_Trigger(in, out, s)
}

func autoConvert_devops_Trigger_To_v1alpha1_Trigger(in *devops.Trigger, out *Trigger, s conversion.Scope) error {
	out.Source = constants.TriggerSource(in.Source)
	out.Event = in.Event
	out.Payload = (*Payload)(unsafe.Pointer(in.Payload))
	return nil
}

// Convert_devops_Trigger_To_v1alpha1_Trigger is an autogenerated conversion function.
func Convert_devops_Trigger_To_v1alpha1_Trigger(in *devops.Trigger, out *Trigger, s conversion.Scope) error {
	return autoConvert_devops_Trigger_To_v1alpha1_Trigger(in, out, s)
}

func autoConvert_v1alpha1_VolumeSpec_To_devops_VolumeSpec(in *VolumeSpec, out *devops.VolumeSpec, s conversion.Scope) error {
	out.Source = in.Source
	out.Destination = in.Destination
	out.Keep = in.Keep
	return nil
}

// Convert_v1alpha1_VolumeSpec_To_devops_VolumeSpec is an autogenerated conversion function.
func Convert_v1alpha1_VolumeSpec_To_devops_VolumeSpec(in *VolumeSpec, out *devops.VolumeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VolumeSpec_To_devops_VolumeSpec(in, out, s)
}

func autoConvert_devops_VolumeSpec_To_v1alpha1_VolumeSpec(in *devops.VolumeSpec, out *VolumeSpec, s conversion.Scope) error {
	out.Source = in.Source
	out.Destination = in.Destination
	out.Keep = in.Keep
	return nil
}

// Convert_devops_VolumeSpec_To_v1alpha1_VolumeSpec is an autogenerated conversion function.
func Convert_devops_VolumeSpec_To_v1alpha1_VolumeSpec(in *devops.VolumeSpec, out *VolumeSpec, s conversion.Scope) error {
	return autoConvert_devops_VolumeSpec_To_v1alpha1_VolumeSpec(in, out, s)
}
