/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package v1alpha1

import (
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"github.com/magicsong/s2iapiserver/pkg/apis/devops"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	devopsKsBuilderStorage = builders.NewApiResource( // Resource status endpoint
		devops.InternalKsBuilder,
		KsBuilderSchemeFns{},
		func() runtime.Object { return &KsBuilder{} },     // Register versioned resource
		func() runtime.Object { return &KsBuilderList{} }, // Register versioned resource list
		&KsBuilderStrategy{builders.StorageStrategySingleton},
	)
	devopsKsBuilderRunStorage = builders.NewApiResource( // Resource status endpoint
		devops.InternalKsBuilderRun,
		KsBuilderRunSchemeFns{},
		func() runtime.Object { return &KsBuilderRun{} },     // Register versioned resource
		func() runtime.Object { return &KsBuilderRunList{} }, // Register versioned resource list
		&KsBuilderRunStrategy{builders.StorageStrategySingleton},
	)
	ApiVersion = builders.NewApiVersion("devops.kubesphere.io", "v1alpha1").WithResources(
		devopsKsBuilderStorage,
		builders.NewApiResource( // Resource status endpoint
			devops.InternalKsBuilderStatus,
			KsBuilderSchemeFns{},
			func() runtime.Object { return &KsBuilder{} },     // Register versioned resource
			func() runtime.Object { return &KsBuilderList{} }, // Register versioned resource list
			&KsBuilderStatusStrategy{builders.StatusStorageStrategySingleton},
		), devopsKsBuilderRunStorage,
		builders.NewApiResource( // Resource status endpoint
			devops.InternalKsBuilderRunStatus,
			KsBuilderRunSchemeFns{},
			func() runtime.Object { return &KsBuilderRun{} },     // Register versioned resource
			func() runtime.Object { return &KsBuilderRunList{} }, // Register versioned resource list
			&KsBuilderRunStatusStrategy{builders.StatusStorageStrategySingleton},
		))

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

//
// KsBuilder Functions and Structs
//
// +k8s:deepcopy-gen=false
type KsBuilderSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type KsBuilderStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type KsBuilderStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type KsBuilderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KsBuilder `json:"items"`
}

//
// KsBuilderRun Functions and Structs
//
// +k8s:deepcopy-gen=false
type KsBuilderRunSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type KsBuilderRunStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type KsBuilderRunStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type KsBuilderRunList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KsBuilderRun `json:"items"`
}
