// +build !ignore_autogenerated

/*
Copyright 2018 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	devops "github.com/magicsong/s2iapiserver/pkg/apis/devops"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_KsBuilder_To_devops_KsBuilder,
		Convert_devops_KsBuilder_To_v1alpha1_KsBuilder,
		Convert_v1alpha1_KsBuilderList_To_devops_KsBuilderList,
		Convert_devops_KsBuilderList_To_v1alpha1_KsBuilderList,
		Convert_v1alpha1_KsBuilderRun_To_devops_KsBuilderRun,
		Convert_devops_KsBuilderRun_To_v1alpha1_KsBuilderRun,
		Convert_v1alpha1_KsBuilderRunList_To_devops_KsBuilderRunList,
		Convert_devops_KsBuilderRunList_To_v1alpha1_KsBuilderRunList,
		Convert_v1alpha1_KsBuilderRunSpec_To_devops_KsBuilderRunSpec,
		Convert_devops_KsBuilderRunSpec_To_v1alpha1_KsBuilderRunSpec,
		Convert_v1alpha1_KsBuilderRunStatus_To_devops_KsBuilderRunStatus,
		Convert_devops_KsBuilderRunStatus_To_v1alpha1_KsBuilderRunStatus,
		Convert_v1alpha1_KsBuilderRunStatusStrategy_To_devops_KsBuilderRunStatusStrategy,
		Convert_devops_KsBuilderRunStatusStrategy_To_v1alpha1_KsBuilderRunStatusStrategy,
		Convert_v1alpha1_KsBuilderRunStrategy_To_devops_KsBuilderRunStrategy,
		Convert_devops_KsBuilderRunStrategy_To_v1alpha1_KsBuilderRunStrategy,
		Convert_v1alpha1_KsBuilderSpec_To_devops_KsBuilderSpec,
		Convert_devops_KsBuilderSpec_To_v1alpha1_KsBuilderSpec,
		Convert_v1alpha1_KsBuilderStatus_To_devops_KsBuilderStatus,
		Convert_devops_KsBuilderStatus_To_v1alpha1_KsBuilderStatus,
		Convert_v1alpha1_KsBuilderStatusStrategy_To_devops_KsBuilderStatusStrategy,
		Convert_devops_KsBuilderStatusStrategy_To_v1alpha1_KsBuilderStatusStrategy,
		Convert_v1alpha1_KsBuilderStrategy_To_devops_KsBuilderStrategy,
		Convert_devops_KsBuilderStrategy_To_v1alpha1_KsBuilderStrategy,
	)
}

func autoConvert_v1alpha1_KsBuilder_To_devops_KsBuilder(in *KsBuilder, out *devops.KsBuilder, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_KsBuilderSpec_To_devops_KsBuilderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_KsBuilderStatus_To_devops_KsBuilderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_KsBuilder_To_devops_KsBuilder is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilder_To_devops_KsBuilder(in *KsBuilder, out *devops.KsBuilder, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilder_To_devops_KsBuilder(in, out, s)
}

func autoConvert_devops_KsBuilder_To_v1alpha1_KsBuilder(in *devops.KsBuilder, out *KsBuilder, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_devops_KsBuilderSpec_To_v1alpha1_KsBuilderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_devops_KsBuilderStatus_To_v1alpha1_KsBuilderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_KsBuilder_To_v1alpha1_KsBuilder is an autogenerated conversion function.
func Convert_devops_KsBuilder_To_v1alpha1_KsBuilder(in *devops.KsBuilder, out *KsBuilder, s conversion.Scope) error {
	return autoConvert_devops_KsBuilder_To_v1alpha1_KsBuilder(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderList_To_devops_KsBuilderList(in *KsBuilderList, out *devops.KsBuilderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]devops.KsBuilder, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_KsBuilder_To_devops_KsBuilder(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_KsBuilderList_To_devops_KsBuilderList is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderList_To_devops_KsBuilderList(in *KsBuilderList, out *devops.KsBuilderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderList_To_devops_KsBuilderList(in, out, s)
}

func autoConvert_devops_KsBuilderList_To_v1alpha1_KsBuilderList(in *devops.KsBuilderList, out *KsBuilderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KsBuilder, len(*in))
		for i := range *in {
			if err := Convert_devops_KsBuilder_To_v1alpha1_KsBuilder(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_devops_KsBuilderList_To_v1alpha1_KsBuilderList is an autogenerated conversion function.
func Convert_devops_KsBuilderList_To_v1alpha1_KsBuilderList(in *devops.KsBuilderList, out *KsBuilderList, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderList_To_v1alpha1_KsBuilderList(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderRun_To_devops_KsBuilderRun(in *KsBuilderRun, out *devops.KsBuilderRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_KsBuilderRunSpec_To_devops_KsBuilderRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_KsBuilderRunStatus_To_devops_KsBuilderRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_KsBuilderRun_To_devops_KsBuilderRun is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderRun_To_devops_KsBuilderRun(in *KsBuilderRun, out *devops.KsBuilderRun, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderRun_To_devops_KsBuilderRun(in, out, s)
}

func autoConvert_devops_KsBuilderRun_To_v1alpha1_KsBuilderRun(in *devops.KsBuilderRun, out *KsBuilderRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_devops_KsBuilderRunSpec_To_v1alpha1_KsBuilderRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_devops_KsBuilderRunStatus_To_v1alpha1_KsBuilderRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_KsBuilderRun_To_v1alpha1_KsBuilderRun is an autogenerated conversion function.
func Convert_devops_KsBuilderRun_To_v1alpha1_KsBuilderRun(in *devops.KsBuilderRun, out *KsBuilderRun, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderRun_To_v1alpha1_KsBuilderRun(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderRunList_To_devops_KsBuilderRunList(in *KsBuilderRunList, out *devops.KsBuilderRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]devops.KsBuilderRun, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_KsBuilderRun_To_devops_KsBuilderRun(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_KsBuilderRunList_To_devops_KsBuilderRunList is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderRunList_To_devops_KsBuilderRunList(in *KsBuilderRunList, out *devops.KsBuilderRunList, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderRunList_To_devops_KsBuilderRunList(in, out, s)
}

func autoConvert_devops_KsBuilderRunList_To_v1alpha1_KsBuilderRunList(in *devops.KsBuilderRunList, out *KsBuilderRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KsBuilderRun, len(*in))
		for i := range *in {
			if err := Convert_devops_KsBuilderRun_To_v1alpha1_KsBuilderRun(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_devops_KsBuilderRunList_To_v1alpha1_KsBuilderRunList is an autogenerated conversion function.
func Convert_devops_KsBuilderRunList_To_v1alpha1_KsBuilderRunList(in *devops.KsBuilderRunList, out *KsBuilderRunList, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderRunList_To_v1alpha1_KsBuilderRunList(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderRunSpec_To_devops_KsBuilderRunSpec(in *KsBuilderRunSpec, out *devops.KsBuilderRunSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_KsBuilderRunSpec_To_devops_KsBuilderRunSpec is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderRunSpec_To_devops_KsBuilderRunSpec(in *KsBuilderRunSpec, out *devops.KsBuilderRunSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderRunSpec_To_devops_KsBuilderRunSpec(in, out, s)
}

func autoConvert_devops_KsBuilderRunSpec_To_v1alpha1_KsBuilderRunSpec(in *devops.KsBuilderRunSpec, out *KsBuilderRunSpec, s conversion.Scope) error {
	return nil
}

// Convert_devops_KsBuilderRunSpec_To_v1alpha1_KsBuilderRunSpec is an autogenerated conversion function.
func Convert_devops_KsBuilderRunSpec_To_v1alpha1_KsBuilderRunSpec(in *devops.KsBuilderRunSpec, out *KsBuilderRunSpec, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderRunSpec_To_v1alpha1_KsBuilderRunSpec(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderRunStatus_To_devops_KsBuilderRunStatus(in *KsBuilderRunStatus, out *devops.KsBuilderRunStatus, s conversion.Scope) error {
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	out.CompletionTime = (*v1.Time)(unsafe.Pointer(in.CompletionTime))
	// WARNING: in.RunState requires manual conversion: inconvertible types (github.com/magicsong/s2iapiserver/pkg/apis/devops/v1alpha1.RunState vs invalid type)
	return nil
}

func autoConvert_devops_KsBuilderRunStatus_To_v1alpha1_KsBuilderRunStatus(in *devops.KsBuilderRunStatus, out *KsBuilderRunStatus, s conversion.Scope) error {
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	out.CompletionTime = (*v1.Time)(unsafe.Pointer(in.CompletionTime))
	// WARNING: in.RunState requires manual conversion: inconvertible types (invalid type vs github.com/magicsong/s2iapiserver/pkg/apis/devops/v1alpha1.RunState)
	return nil
}

func autoConvert_v1alpha1_KsBuilderRunStatusStrategy_To_devops_KsBuilderRunStatusStrategy(in *KsBuilderRunStatusStrategy, out *devops.KsBuilderRunStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_KsBuilderRunStatusStrategy_To_devops_KsBuilderRunStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderRunStatusStrategy_To_devops_KsBuilderRunStatusStrategy(in *KsBuilderRunStatusStrategy, out *devops.KsBuilderRunStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderRunStatusStrategy_To_devops_KsBuilderRunStatusStrategy(in, out, s)
}

func autoConvert_devops_KsBuilderRunStatusStrategy_To_v1alpha1_KsBuilderRunStatusStrategy(in *devops.KsBuilderRunStatusStrategy, out *KsBuilderRunStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_devops_KsBuilderRunStatusStrategy_To_v1alpha1_KsBuilderRunStatusStrategy is an autogenerated conversion function.
func Convert_devops_KsBuilderRunStatusStrategy_To_v1alpha1_KsBuilderRunStatusStrategy(in *devops.KsBuilderRunStatusStrategy, out *KsBuilderRunStatusStrategy, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderRunStatusStrategy_To_v1alpha1_KsBuilderRunStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderRunStrategy_To_devops_KsBuilderRunStrategy(in *KsBuilderRunStrategy, out *devops.KsBuilderRunStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_KsBuilderRunStrategy_To_devops_KsBuilderRunStrategy is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderRunStrategy_To_devops_KsBuilderRunStrategy(in *KsBuilderRunStrategy, out *devops.KsBuilderRunStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderRunStrategy_To_devops_KsBuilderRunStrategy(in, out, s)
}

func autoConvert_devops_KsBuilderRunStrategy_To_v1alpha1_KsBuilderRunStrategy(in *devops.KsBuilderRunStrategy, out *KsBuilderRunStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_devops_KsBuilderRunStrategy_To_v1alpha1_KsBuilderRunStrategy is an autogenerated conversion function.
func Convert_devops_KsBuilderRunStrategy_To_v1alpha1_KsBuilderRunStrategy(in *devops.KsBuilderRunStrategy, out *KsBuilderRunStrategy, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderRunStrategy_To_v1alpha1_KsBuilderRunStrategy(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderSpec_To_devops_KsBuilderSpec(in *KsBuilderSpec, out *devops.KsBuilderSpec, s conversion.Scope) error {
	out.Config = in.Config
	return nil
}

// Convert_v1alpha1_KsBuilderSpec_To_devops_KsBuilderSpec is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderSpec_To_devops_KsBuilderSpec(in *KsBuilderSpec, out *devops.KsBuilderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderSpec_To_devops_KsBuilderSpec(in, out, s)
}

func autoConvert_devops_KsBuilderSpec_To_v1alpha1_KsBuilderSpec(in *devops.KsBuilderSpec, out *KsBuilderSpec, s conversion.Scope) error {
	out.Config = in.Config
	return nil
}

// Convert_devops_KsBuilderSpec_To_v1alpha1_KsBuilderSpec is an autogenerated conversion function.
func Convert_devops_KsBuilderSpec_To_v1alpha1_KsBuilderSpec(in *devops.KsBuilderSpec, out *KsBuilderSpec, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderSpec_To_v1alpha1_KsBuilderSpec(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderStatus_To_devops_KsBuilderStatus(in *KsBuilderStatus, out *devops.KsBuilderStatus, s conversion.Scope) error {
	out.RunCount = in.RunCount
	// WARNING: in.LastRunState requires manual conversion: inconvertible types (github.com/magicsong/s2iapiserver/pkg/apis/devops/v1alpha1.RunState vs invalid type)
	out.LastRunName = in.LastRunName
	return nil
}

func autoConvert_devops_KsBuilderStatus_To_v1alpha1_KsBuilderStatus(in *devops.KsBuilderStatus, out *KsBuilderStatus, s conversion.Scope) error {
	out.RunCount = in.RunCount
	// WARNING: in.LastRunState requires manual conversion: inconvertible types (invalid type vs github.com/magicsong/s2iapiserver/pkg/apis/devops/v1alpha1.RunState)
	out.LastRunName = in.LastRunName
	return nil
}

func autoConvert_v1alpha1_KsBuilderStatusStrategy_To_devops_KsBuilderStatusStrategy(in *KsBuilderStatusStrategy, out *devops.KsBuilderStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_KsBuilderStatusStrategy_To_devops_KsBuilderStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderStatusStrategy_To_devops_KsBuilderStatusStrategy(in *KsBuilderStatusStrategy, out *devops.KsBuilderStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderStatusStrategy_To_devops_KsBuilderStatusStrategy(in, out, s)
}

func autoConvert_devops_KsBuilderStatusStrategy_To_v1alpha1_KsBuilderStatusStrategy(in *devops.KsBuilderStatusStrategy, out *KsBuilderStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_devops_KsBuilderStatusStrategy_To_v1alpha1_KsBuilderStatusStrategy is an autogenerated conversion function.
func Convert_devops_KsBuilderStatusStrategy_To_v1alpha1_KsBuilderStatusStrategy(in *devops.KsBuilderStatusStrategy, out *KsBuilderStatusStrategy, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderStatusStrategy_To_v1alpha1_KsBuilderStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_KsBuilderStrategy_To_devops_KsBuilderStrategy(in *KsBuilderStrategy, out *devops.KsBuilderStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_KsBuilderStrategy_To_devops_KsBuilderStrategy is an autogenerated conversion function.
func Convert_v1alpha1_KsBuilderStrategy_To_devops_KsBuilderStrategy(in *KsBuilderStrategy, out *devops.KsBuilderStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_KsBuilderStrategy_To_devops_KsBuilderStrategy(in, out, s)
}

func autoConvert_devops_KsBuilderStrategy_To_v1alpha1_KsBuilderStrategy(in *devops.KsBuilderStrategy, out *KsBuilderStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_devops_KsBuilderStrategy_To_v1alpha1_KsBuilderStrategy is an autogenerated conversion function.
func Convert_devops_KsBuilderStrategy_To_v1alpha1_KsBuilderStrategy(in *devops.KsBuilderStrategy, out *KsBuilderStrategy, s conversion.Scope) error {
	return autoConvert_devops_KsBuilderStrategy_To_v1alpha1_KsBuilderStrategy(in, out, s)
}
