// +build !ignore_autogenerated

/*
Copyright 2018 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	devops "github.com/magicsong/s2iapiserver/pkg/apis/devops"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*S2iBuilder)(nil), (*devops.S2iBuilder)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilder_To_devops_S2iBuilder(a.(*S2iBuilder), b.(*devops.S2iBuilder), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilder)(nil), (*S2iBuilder)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilder_To_v1alpha1_S2iBuilder(a.(*devops.S2iBuilder), b.(*S2iBuilder), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderList)(nil), (*devops.S2iBuilderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList(a.(*S2iBuilderList), b.(*devops.S2iBuilderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderList)(nil), (*S2iBuilderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList(a.(*devops.S2iBuilderList), b.(*S2iBuilderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderSpec)(nil), (*devops.S2iBuilderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(a.(*S2iBuilderSpec), b.(*devops.S2iBuilderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderSpec)(nil), (*S2iBuilderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(a.(*devops.S2iBuilderSpec), b.(*S2iBuilderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderStatus)(nil), (*devops.S2iBuilderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(a.(*S2iBuilderStatus), b.(*devops.S2iBuilderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderStatus)(nil), (*S2iBuilderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(a.(*devops.S2iBuilderStatus), b.(*S2iBuilderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderStatusStrategy)(nil), (*devops.S2iBuilderStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy(a.(*S2iBuilderStatusStrategy), b.(*devops.S2iBuilderStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderStatusStrategy)(nil), (*S2iBuilderStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy(a.(*devops.S2iBuilderStatusStrategy), b.(*S2iBuilderStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iBuilderStrategy)(nil), (*devops.S2iBuilderStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy(a.(*S2iBuilderStrategy), b.(*devops.S2iBuilderStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iBuilderStrategy)(nil), (*S2iBuilderStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy(a.(*devops.S2iBuilderStrategy), b.(*S2iBuilderStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRun)(nil), (*devops.S2iRun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRun_To_devops_S2iRun(a.(*S2iRun), b.(*devops.S2iRun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRun)(nil), (*S2iRun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRun_To_v1alpha1_S2iRun(a.(*devops.S2iRun), b.(*S2iRun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunList)(nil), (*devops.S2iRunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunList_To_devops_S2iRunList(a.(*S2iRunList), b.(*devops.S2iRunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunList)(nil), (*S2iRunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunList_To_v1alpha1_S2iRunList(a.(*devops.S2iRunList), b.(*S2iRunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunSpec)(nil), (*devops.S2iRunSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(a.(*S2iRunSpec), b.(*devops.S2iRunSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunSpec)(nil), (*S2iRunSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(a.(*devops.S2iRunSpec), b.(*S2iRunSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunStatus)(nil), (*devops.S2iRunStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(a.(*S2iRunStatus), b.(*devops.S2iRunStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunStatus)(nil), (*S2iRunStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(a.(*devops.S2iRunStatus), b.(*S2iRunStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunStatusStrategy)(nil), (*devops.S2iRunStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy(a.(*S2iRunStatusStrategy), b.(*devops.S2iRunStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunStatusStrategy)(nil), (*S2iRunStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy(a.(*devops.S2iRunStatusStrategy), b.(*S2iRunStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S2iRunStrategy)(nil), (*devops.S2iRunStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy(a.(*S2iRunStrategy), b.(*devops.S2iRunStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.S2iRunStrategy)(nil), (*S2iRunStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy(a.(*devops.S2iRunStrategy), b.(*S2iRunStrategy), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_S2iBuilder_To_devops_S2iBuilder(in *S2iBuilder, out *devops.S2iBuilder, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_S2iBuilder_To_devops_S2iBuilder is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilder_To_devops_S2iBuilder(in *S2iBuilder, out *devops.S2iBuilder, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilder_To_devops_S2iBuilder(in, out, s)
}

func autoConvert_devops_S2iBuilder_To_v1alpha1_S2iBuilder(in *devops.S2iBuilder, out *S2iBuilder, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_S2iBuilder_To_v1alpha1_S2iBuilder is an autogenerated conversion function.
func Convert_devops_S2iBuilder_To_v1alpha1_S2iBuilder(in *devops.S2iBuilder, out *S2iBuilder, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilder_To_v1alpha1_S2iBuilder(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList(in *S2iBuilderList, out *devops.S2iBuilderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]devops.S2iBuilder)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList(in *S2iBuilderList, out *devops.S2iBuilderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderList_To_devops_S2iBuilderList(in, out, s)
}

func autoConvert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList(in *devops.S2iBuilderList, out *S2iBuilderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]S2iBuilder)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList is an autogenerated conversion function.
func Convert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList(in *devops.S2iBuilderList, out *S2iBuilderList, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderList_To_v1alpha1_S2iBuilderList(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(in *S2iBuilderSpec, out *devops.S2iBuilderSpec, s conversion.Scope) error {
	out.Config = in.Config
	return nil
}

// Convert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(in *S2iBuilderSpec, out *devops.S2iBuilderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderSpec_To_devops_S2iBuilderSpec(in, out, s)
}

func autoConvert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(in *devops.S2iBuilderSpec, out *S2iBuilderSpec, s conversion.Scope) error {
	out.Config = in.Config
	return nil
}

// Convert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec is an autogenerated conversion function.
func Convert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(in *devops.S2iBuilderSpec, out *S2iBuilderSpec, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderSpec_To_v1alpha1_S2iBuilderSpec(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(in *S2iBuilderStatus, out *devops.S2iBuilderStatus, s conversion.Scope) error {
	out.RunCount = in.RunCount
	out.LastRunState = in.LastRunState
	out.LastRunName = (*string)(unsafe.Pointer(in.LastRunName))
	return nil
}

// Convert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(in *S2iBuilderStatus, out *devops.S2iBuilderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderStatus_To_devops_S2iBuilderStatus(in, out, s)
}

func autoConvert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(in *devops.S2iBuilderStatus, out *S2iBuilderStatus, s conversion.Scope) error {
	out.RunCount = in.RunCount
	out.LastRunState = in.LastRunState
	out.LastRunName = (*string)(unsafe.Pointer(in.LastRunName))
	return nil
}

// Convert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus is an autogenerated conversion function.
func Convert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(in *devops.S2iBuilderStatus, out *S2iBuilderStatus, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderStatus_To_v1alpha1_S2iBuilderStatus(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy(in *S2iBuilderStatusStrategy, out *devops.S2iBuilderStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy(in *S2iBuilderStatusStrategy, out *devops.S2iBuilderStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderStatusStrategy_To_devops_S2iBuilderStatusStrategy(in, out, s)
}

func autoConvert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy(in *devops.S2iBuilderStatusStrategy, out *S2iBuilderStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy is an autogenerated conversion function.
func Convert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy(in *devops.S2iBuilderStatusStrategy, out *S2iBuilderStatusStrategy, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderStatusStrategy_To_v1alpha1_S2iBuilderStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy(in *S2iBuilderStrategy, out *devops.S2iBuilderStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy is an autogenerated conversion function.
func Convert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy(in *S2iBuilderStrategy, out *devops.S2iBuilderStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iBuilderStrategy_To_devops_S2iBuilderStrategy(in, out, s)
}

func autoConvert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy(in *devops.S2iBuilderStrategy, out *S2iBuilderStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy is an autogenerated conversion function.
func Convert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy(in *devops.S2iBuilderStrategy, out *S2iBuilderStrategy, s conversion.Scope) error {
	return autoConvert_devops_S2iBuilderStrategy_To_v1alpha1_S2iBuilderStrategy(in, out, s)
}

func autoConvert_v1alpha1_S2iRun_To_devops_S2iRun(in *S2iRun, out *devops.S2iRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_S2iRun_To_devops_S2iRun is an autogenerated conversion function.
func Convert_v1alpha1_S2iRun_To_devops_S2iRun(in *S2iRun, out *devops.S2iRun, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRun_To_devops_S2iRun(in, out, s)
}

func autoConvert_devops_S2iRun_To_v1alpha1_S2iRun(in *devops.S2iRun, out *S2iRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_S2iRun_To_v1alpha1_S2iRun is an autogenerated conversion function.
func Convert_devops_S2iRun_To_v1alpha1_S2iRun(in *devops.S2iRun, out *S2iRun, s conversion.Scope) error {
	return autoConvert_devops_S2iRun_To_v1alpha1_S2iRun(in, out, s)
}

func autoConvert_v1alpha1_S2iRunList_To_devops_S2iRunList(in *S2iRunList, out *devops.S2iRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]devops.S2iRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_S2iRunList_To_devops_S2iRunList is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunList_To_devops_S2iRunList(in *S2iRunList, out *devops.S2iRunList, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunList_To_devops_S2iRunList(in, out, s)
}

func autoConvert_devops_S2iRunList_To_v1alpha1_S2iRunList(in *devops.S2iRunList, out *S2iRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]S2iRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_devops_S2iRunList_To_v1alpha1_S2iRunList is an autogenerated conversion function.
func Convert_devops_S2iRunList_To_v1alpha1_S2iRunList(in *devops.S2iRunList, out *S2iRunList, s conversion.Scope) error {
	return autoConvert_devops_S2iRunList_To_v1alpha1_S2iRunList(in, out, s)
}

func autoConvert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(in *S2iRunSpec, out *devops.S2iRunSpec, s conversion.Scope) error {
	out.BuilderName = in.BuilderName
	out.BackoffLimit = in.BackoffLimit
	out.SecondsAfterFinished = in.SecondsAfterFinished
	return nil
}

// Convert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(in *S2iRunSpec, out *devops.S2iRunSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunSpec_To_devops_S2iRunSpec(in, out, s)
}

func autoConvert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(in *devops.S2iRunSpec, out *S2iRunSpec, s conversion.Scope) error {
	out.BuilderName = in.BuilderName
	out.BackoffLimit = in.BackoffLimit
	out.SecondsAfterFinished = in.SecondsAfterFinished
	return nil
}

// Convert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec is an autogenerated conversion function.
func Convert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(in *devops.S2iRunSpec, out *S2iRunSpec, s conversion.Scope) error {
	return autoConvert_devops_S2iRunSpec_To_v1alpha1_S2iRunSpec(in, out, s)
}

func autoConvert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(in *S2iRunStatus, out *devops.S2iRunStatus, s conversion.Scope) error {
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	out.CompletionTime = (*v1.Time)(unsafe.Pointer(in.CompletionTime))
	out.RunState = in.RunState
	return nil
}

// Convert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(in *S2iRunStatus, out *devops.S2iRunStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunStatus_To_devops_S2iRunStatus(in, out, s)
}

func autoConvert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(in *devops.S2iRunStatus, out *S2iRunStatus, s conversion.Scope) error {
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	out.CompletionTime = (*v1.Time)(unsafe.Pointer(in.CompletionTime))
	out.RunState = in.RunState
	return nil
}

// Convert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus is an autogenerated conversion function.
func Convert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(in *devops.S2iRunStatus, out *S2iRunStatus, s conversion.Scope) error {
	return autoConvert_devops_S2iRunStatus_To_v1alpha1_S2iRunStatus(in, out, s)
}

func autoConvert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy(in *S2iRunStatusStrategy, out *devops.S2iRunStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy(in *S2iRunStatusStrategy, out *devops.S2iRunStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunStatusStrategy_To_devops_S2iRunStatusStrategy(in, out, s)
}

func autoConvert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy(in *devops.S2iRunStatusStrategy, out *S2iRunStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy is an autogenerated conversion function.
func Convert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy(in *devops.S2iRunStatusStrategy, out *S2iRunStatusStrategy, s conversion.Scope) error {
	return autoConvert_devops_S2iRunStatusStrategy_To_v1alpha1_S2iRunStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy(in *S2iRunStrategy, out *devops.S2iRunStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy is an autogenerated conversion function.
func Convert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy(in *S2iRunStrategy, out *devops.S2iRunStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_S2iRunStrategy_To_devops_S2iRunStrategy(in, out, s)
}

func autoConvert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy(in *devops.S2iRunStrategy, out *S2iRunStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy is an autogenerated conversion function.
func Convert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy(in *devops.S2iRunStrategy, out *S2iRunStrategy, s conversion.Scope) error {
	return autoConvert_devops_S2iRunStrategy_To_v1alpha1_S2iRunStrategy(in, out, s)
}
