/*
Copyright 2018 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/magicsong/s2iapiserver/pkg/apis/devops/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReruns implements RerunInterface
type FakeReruns struct {
	Fake *FakeDevopsV1alpha1
	ns   string
}

var rerunsResource = schema.GroupVersionResource{Group: "devops.kubesphere.io", Version: "v1alpha1", Resource: "reruns"}

var rerunsKind = schema.GroupVersionKind{Group: "devops.kubesphere.io", Version: "v1alpha1", Kind: "Rerun"}

// Get takes name of the rerun, and returns the corresponding rerun object, and an error if there is any.
func (c *FakeReruns) Get(name string, options v1.GetOptions) (result *v1alpha1.Rerun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rerunsResource, c.ns, name), &v1alpha1.Rerun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rerun), err
}

// List takes label and field selectors, and returns the list of Reruns that match those selectors.
func (c *FakeReruns) List(opts v1.ListOptions) (result *v1alpha1.RerunList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rerunsResource, rerunsKind, c.ns, opts), &v1alpha1.RerunList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RerunList{ListMeta: obj.(*v1alpha1.RerunList).ListMeta}
	for _, item := range obj.(*v1alpha1.RerunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested reruns.
func (c *FakeReruns) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rerunsResource, c.ns, opts))

}

// Create takes the representation of a rerun and creates it.  Returns the server's representation of the rerun, and an error, if there is any.
func (c *FakeReruns) Create(rerun *v1alpha1.Rerun) (result *v1alpha1.Rerun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rerunsResource, c.ns, rerun), &v1alpha1.Rerun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rerun), err
}

// Update takes the representation of a rerun and updates it. Returns the server's representation of the rerun, and an error, if there is any.
func (c *FakeReruns) Update(rerun *v1alpha1.Rerun) (result *v1alpha1.Rerun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rerunsResource, c.ns, rerun), &v1alpha1.Rerun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rerun), err
}

// Delete takes name of the rerun and deletes it. Returns an error if one occurs.
func (c *FakeReruns) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rerunsResource, c.ns, name), &v1alpha1.Rerun{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReruns) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rerunsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RerunList{})
	return err
}

// Patch applies the patch and returns the patched rerun.
func (c *FakeReruns) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Rerun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rerunsResource, c.ns, name, data, subresources...), &v1alpha1.Rerun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rerun), err
}
