/*
Copyright 2018 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// This file was automatically generated by informer-gen

package internalversion

import (
	devops "github.com/magicsong/s2iapiserver/pkg/apis/devops"
	internalclientset "github.com/magicsong/s2iapiserver/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/magicsong/s2iapiserver/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/magicsong/s2iapiserver/pkg/client/listers_generated/devops/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// KsBuilderRunInformer provides access to a shared informer and lister for
// KsBuilderRuns.
type KsBuilderRunInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.KsBuilderRunLister
}

type ksBuilderRunInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKsBuilderRunInformer constructs a new informer for KsBuilderRun type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKsBuilderRunInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKsBuilderRunInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKsBuilderRunInformer constructs a new informer for KsBuilderRun type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKsBuilderRunInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Devops().KsBuilderRuns(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Devops().KsBuilderRuns(namespace).Watch(options)
			},
		},
		&devops.KsBuilderRun{},
		resyncPeriod,
		indexers,
	)
}

func (f *ksBuilderRunInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKsBuilderRunInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ksBuilderRunInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&devops.KsBuilderRun{}, f.defaultInformer)
}

func (f *ksBuilderRunInformer) Lister() internalversion.KsBuilderRunLister {
	return internalversion.NewKsBuilderRunLister(f.Informer().GetIndexer())
}
