/*
Copyright 2018 The Kubesphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// This file was automatically generated by informer-gen

package internalversion

import (
	devops "github.com/magicsong/s2iapiserver/pkg/apis/devops"
	internalclientset "github.com/magicsong/s2iapiserver/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/magicsong/s2iapiserver/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/magicsong/s2iapiserver/pkg/client/listers_generated/devops/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// KsBuilderInformer provides access to a shared informer and lister for
// KsBuilders.
type KsBuilderInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.KsBuilderLister
}

type ksBuilderInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKsBuilderInformer constructs a new informer for KsBuilder type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKsBuilderInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKsBuilderInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKsBuilderInformer constructs a new informer for KsBuilder type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKsBuilderInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Devops().KsBuilders(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Devops().KsBuilders(namespace).Watch(options)
			},
		},
		&devops.KsBuilder{},
		resyncPeriod,
		indexers,
	)
}

func (f *ksBuilderInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKsBuilderInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ksBuilderInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&devops.KsBuilder{}, f.defaultInformer)
}

func (f *ksBuilderInformer) Lister() internalversion.KsBuilderLister {
	return internalversion.NewKsBuilderLister(f.Informer().GetIndexer())
}
