
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.devops.kubesphere.io
  labels:
    api: s2iapiserver
    apiserver: "true"
spec:
  version: v1alpha1
  group: devops.kubesphere.io
  groupPriorityMinimum: 2000
  service:
    name: s2iapiserver
    namespace: devops
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyakNDQXBhZ0F3SUJBZ0lKQUlwRmZlTnF5TExjTUEwR0NTcUdTSWIzRFFFQkN3VUFNR3d4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhLekFwQmdOVkJBTU1Jbk15YVdGd2FYTmxjblpsY2kxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3SGhjTk1UZ3hNakEyTURNMU5EUXdXaGNOTVRreE1qQTJNRE0xTkRRd1dqQnNNUXN3Q1FZRFZRUUcKRXdKMWJqRUxNQWtHQTFVRUNBd0NjM1F4Q2pBSUJnTlZCQWNNQVd3eENqQUlCZ05WQkFvTUFXOHhDekFKQmdOVgpCQXNNQW05MU1Tc3dLUVlEVlFRRERDSnpNbWxoY0dselpYSjJaWEl0WTJWeWRHbG1hV05oZEdVdFlYVjBhRzl5CmFYUjVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXJ5a1g3d25xRDVLdzBmMnkKTnppbXBVUko4Yk9MMmd5anZxUjJWRFdiNmlNdk9ndTNPZkVYR2ZFZldJdkgwdStJRi9ZaGtDQ0R3VDBJUlJKYQpTbExKL1FZYmVRdXZZSTdLNkoxVUdOOHdDR3QyT2RhMkc1UTlWL3FxKzNDNWErTHoveVhsUDRrVVZJekY3c3E4CkFWekZmbVBJVkk2MTUySGtUMG1sbWNWZ0g4ZEl6RzJHVyt6WnppZTZ5RGRmREN1NGJvakE1enpLbk5sN01UZk0KV25QZU8rM2U5dmlTem5wQVJVOWFQUmZncFhVWko2OHRsYldxaitqTjhYeFNKVHBVQjdLRnh1NlYxS2hPMTU4KwozeHpLbkNXZ0x0Q2hsbDl3a0NlTTRJeHRuaVd4MjJXNzRweWcrYUh1c2xJaEQwOHdGbUIzOUZpcmJaQitNVGM0CmZ6YmdRUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVcTU1NmF6ZFVhUjcxczEzbWhYNk5Kb2hEMThnd0h3WUQKVlIwakJCZ3dGb0FVcTU1NmF6ZFVhUjcxczEzbWhYNk5Kb2hEMThnd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHMkk2U0JBN3RLTlk2N1FXenVMY3p3TmlGYU9xTFV2ZStxd1ZiVXdWCmZpczJZTzZZelVQV1RJKzlRYkxqVHhORHdsSUxmdkJodnI2dXpNbXNoK1MxdDZHWWpreDNqMEpqOWJlUlJPYXoKRW4wV3hXTG1yak8yWEdaSVJxME40ZzByU1VPWUNiT2pmMVhzc0hVTGJJYnB1TEE4UEJqdkVGQWJpKzJ6YXZmSApOZUVGOU5yRFR4NzdlamRaM1h4K3hnSUpnTERvV2htSlZLNHlBcks1eTArblZVUjYrN1pRSE1YeTRkdkNUK3UyCms5TmpJVWpVb1hDSE5FTDZUb1htNVdpSmpSVjVBd1RZaDdFRUNUZXFqcVdhZWF4ckhYUWxyZTJUNWhielRxd2QKWEdNMDNIbjJHS3ZUWncyYmhlWWJONGdBQnNWWDhkeXZzbjdMRVI5M2JhTHVCQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: v1
kind: Service
metadata:
  name: s2iapiserver
  namespace: devops
  labels:
    api: s2iapiserver
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: s2iapiserver
    apiserver: "true"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: s2iapiserver
  namespace: devops
  labels:
    api: s2iapiserver
    apiserver: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        api: s2iapiserver
        apiserver: "true"
    spec:
      imagePullSecrets:
      - name: s2i-pull-secret
      
      serviceAccount: s2i-service-account
      containers:
      - name: apiserver
        image: dockerhub.qingcloud.com/magicsong/s2iapiserver:93f63fd5
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        - "--loglevel=3"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: controller
        image: dockerhub.qingcloud.com/magicsong/s2iapiserver:93f63fd5
        command:
        - "./controller-manager"
        args:
        - "-v=3"
        - "-logtostderr=true"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: s2iapiserver
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: etcd
  namespace: devops
spec:
  serviceName: "etcd"
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
        env:
        - name: ETCD_DATA_DIR
          value: /etcd-data-dir
        command:
        - /usr/local/bin/etcd
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://localhost:2379
        ports:
        - containerPort: 2379
        volumeMounts:
        - name: etcd-data-dir
          mountPath: /etcd-data-dir
        readinessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
  volumeClaimTemplates:
  - metadata:
     name: etcd-data-dir
     annotations:
        volume.beta.kubernetes.io/storage-class: gluster-heketi
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
         storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: devops
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: etcd
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: s2iapiserver
  namespace: devops
  labels:
    api: s2iapiserver
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTVENDQWpFQ0NRREpmenFGS21DUDREQU5CZ2txaGtpRzl3MEJBUXNGQURCc01Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVNzd0tRWURWUVFERENKek1tbGhjR2x6WlhKMlpYSXRZMlZ5ZEdsbWFXTmhkR1V0WVhWMGFHOXlhWFI1Ck1CNFhEVEU0TVRJd05qQXpOVFEwTUZvWERURTVNVEl3TmpBek5UUTBNRm93WVRFTE1Ba0dBMVVFQmhNQ2RXNHgKQ3pBSkJnTlZCQWdNQW5OME1Rb3dDQVlEVlFRSERBRnNNUW93Q0FZRFZRUUtEQUZ2TVFzd0NRWURWUVFMREFKdgpkVEVnTUI0R0ExVUVBd3dYY3pKcFlYQnBjMlZ5ZG1WeUxtUmxkbTl3Y3k1emRtTXdnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2F2ei9PSWJRaks4YnFTYmE3Tkd0WDUvaXpZdU0yYzVic3ltRysKa2VrTzRkcFlYdEtSbWpaejRQb1ZiQ0NxcWhUWXF3Vk44b0oxK005T0gxQmYyaXFBdG95Zm82bEVNQVo1VTJDRApwTjRQdEl5UEZSQy82ZDcvWDNna3pWZVdzYStZTThEWFVCQTJ1SVorSm0wN0NHY09veFE3OGlxd29hanR4dVFoCnViR1hDN0VrenZ5YTVCZ3lrQTVtb1RNMndBcGw4bEtpaTd3YzB3UVZZZHpOQ2NHNk1VbHdCNEJ3Z2xxRnZIcm8KQnJCRkp2dFpCYTBwZ1c0Q3hNdFF0YnRDNXExeFUwbjE1RTBqdmp1dHRPM3JISEVtOHNCVHFLcHRDRHF1SjI1NgpiTEd5cGFaN2sreWhZY3pQaWdETEcxLzk2MFo1QUJxMFpLR2c1WThiYzZ4am9YY1ZBZ01CQUFFd0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnRUJBS0dyeWNsWXNSSng4RUNIc0ZBcjNjT3FYc2lLM1R1b2taK1BkV0Q4NHFKZ1luZm8KY1hnTG9Xb0lndjVNRkVjNTBFdzNmYXdXVjBGSXVsZFk1eEJQT01rYlZRU3U0QkdQOFFBajJzWlBEUlp2eVdDTQpaa21Jb1ZMU2E5L011Yjd1cjR5YWFNUFFCNDMrYUdrUWtFd3IrbWc1cFZzTGQrMUJLVHQ2b0tuQUZ2OXN2QUE2CkNyS3FWM1FVNitwK29GUDhrQ2JSTEVHdGpmTGNKV0NBSFZSVUxTOHZQN0FKNTd5bWpyU3puYThoT2VjSUkvUmsKWkNhU25SdTlmTVdPNmQzZ1VsVUxiMm1hREwyQm1oOXUyd3A0cE5sNFR5RE4zaFZST3ZmTUhIMDFrZ3ZLQXAyMwpuWklTQVAvQUE3bmppUCtSYlh0a25TejZpc1o3T2lxOWRCT0U0azg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQ2F2ei9PSWJRaks4YnEKU2JhN05HdFg1L2l6WXVNMmM1YnN5bUcra2VrTzRkcFlYdEtSbWpaejRQb1ZiQ0NxcWhUWXF3Vk44b0oxK005TwpIMUJmMmlxQXRveWZvNmxFTUFaNVUyQ0RwTjRQdEl5UEZSQy82ZDcvWDNna3pWZVdzYStZTThEWFVCQTJ1SVorCkptMDdDR2NPb3hRNzhpcXdvYWp0eHVRaHViR1hDN0VrenZ5YTVCZ3lrQTVtb1RNMndBcGw4bEtpaTd3YzB3UVYKWWR6TkNjRzZNVWx3QjRCd2dscUZ2SHJvQnJCRkp2dFpCYTBwZ1c0Q3hNdFF0YnRDNXExeFUwbjE1RTBqdmp1dAp0TzNySEhFbThzQlRxS3B0Q0RxdUoyNTZiTEd5cGFaN2sreWhZY3pQaWdETEcxLzk2MFo1QUJxMFpLR2c1WThiCmM2eGpvWGNWQWdNQkFBRUNnZ0VBRmZNcXljSmVHdDhLeUJETXFxRTAyTE0rdzdNekozWWQ0bGlTcE1WdG1YN1AKeWRrcFpSM0t1NFVkOUF2eVZrTHAwaEh3SHE1WGN3Um40MXp0dWFyb2ZIbG9XUHlOOWU0Wi9QdW1wUVd0dWV5UwpRM2xwZHM5bG9qT1loeC9aWExhM2dZOVZ1elRRRi9MMG9OQXlqajBTNFRDZ25pQXJqZ0pnUTlvQ1lnWkUrbmVsCm5oN2p2c3JvbTdiVHNNcThRUFUySlRJQzNoUUNVdTN2R0txRlRqclhLeWVsYUxPUzlyd0p5dmhaUHhqWVRqaVQKT2g0My92WS9PRWNOZkk0QlpiZUZMQ3RkNzcrei9QWC9kWW5pRTJYSHpMbk1WTjZYQnhrelF1WW1Rb0JkYTZYZAo0MytYb2grN2lpUDN2TXB1Wm5oZEl5NXVyN2VYcS9PVW1YaTNSbTh0d1FLQmdRRExwWlNzY1ZmMGhQM0t2ZGR4CkF3QmM2Z3JBYzEyZzdtNkZ4a3VPTUZBN1JIYVk3Y0k3Tk1Rc2t2TnN1Ung5YkZVUlFwWXdkN1J4VjFacFpSUWsKemxXaDVqOUNwNGVDOUpTSmdZM1VqWmRpanpBa1NYN3Rnb1MzRjZnOVJINGR3NGluSElCc3dTSW8vTWh6aTB6ZwpxQTJUcDVwRWVzUE5rbERUK3Q2Vi9vVFBxd0tCZ1FEQ2gzbTJBbDZOUG96K1JiRXFUcFlRVmpvdmU2aVdYUmRVClJMQWpvWkZIdWc3VkVoc1hJQUxtME14MjJIN3NtQVpPNmxWdXJCNytDRHFyMkY0NnREWDZRZXVuWXJJcXhaUnMKclhBSVFZdGJvZG0yZzNrcGw2dkVCcGgrOWt6Zlk4bDFNeFZsWkR0TVR3WThtRSs3UEIreExadjdTY0ljcVY2RgpBeUtCZlNzVVB3S0JnUUNWMmkwUnk0RytZNUpoZXRxcXhWdWlBM0tQOVJTRGxJL3RqbUlRcWtxUG9peG5FaVduCjdZY2hpYXpvWnpxb3JHdllmSmdKNkR2Mlh4OHVCUHdTcldaajhRckI0SWNkL1IzRUpYb1pXMnQzVWdoSjIyODAKRktQV0d1bG8xQnE5aWlIblhsaStMa3dWdnhVOXVOYUVSZ1ZmanFnOUZkMDVTeDZCTGd4V2NXaUhhd0tCZ1FDOQpVU1dsZWZiVkZXd1lSbkVlVUc4QkpUbnBYanA3WTh2QmlqdTE0WmJITEk4azFFTWpKVmRObFNWNEFFaStMMUhzCldXaWRsY3R2eFVoOFY4MlU2aStpQjZlMU5udFkzd01OSlZuajN3NG1Ob1R3ZUZGaHBpZFhWbWZ4SC9rK2F4bjAKQXF3dkNmWWYxTVNvRWo5K1pBd2YzZGh4SFo1WlVJZ1pnU3lDd3ZNNjl3S0JnUUNLbkMySHovUkNjT25ITmZLRApSZFJXUUJCbGZXY29WVkVDU3ZObkMyMlBwYmtsR0tqY2p1US92R2NydnY0bndUNldWRFZpQlQ5cXM1YXVUTmdSCjg2aEorS3hta3pJZm4yWU1iazBHQ1FnLzVDZFZsU0lhTEQ1MDlvM1FuYmhLalM3NHI2RGJtLzFCK0tzbHZOM2YKQTM2M1RDbmVWQStJMlo0c09vY20xR0hBMUE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
