/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package devops

import (
	"fmt"

	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	pkgapi "github.com/magicsong/s2irun/pkg/api"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalKsBuilder = builders.NewInternalResource(
		"ksbuilders",
		"KsBuilder",
		func() runtime.Object { return &KsBuilder{} },
		func() runtime.Object { return &KsBuilderList{} },
	)
	InternalKsBuilderStatus = builders.NewInternalResourceStatus(
		"ksbuilders",
		"KsBuilderStatus",
		func() runtime.Object { return &KsBuilder{} },
		func() runtime.Object { return &KsBuilderList{} },
	)
	InternalKsBuilderRun = builders.NewInternalResource(
		"ksbuilderruns",
		"KsBuilderRun",
		func() runtime.Object { return &KsBuilderRun{} },
		func() runtime.Object { return &KsBuilderRunList{} },
	)
	InternalKsBuilderRunStatus = builders.NewInternalResourceStatus(
		"ksbuilderruns",
		"KsBuilderRunStatus",
		func() runtime.Object { return &KsBuilderRun{} },
		func() runtime.Object { return &KsBuilderRunList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("devops.kubesphere.io").WithKinds(
		InternalKsBuilder,
		InternalKsBuilderStatus,
		InternalKsBuilderRun,
		InternalKsBuilderRunStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type KsBuilder struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   KsBuilderSpec
	Status KsBuilderStatus
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type KsBuilderRun struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   KsBuilderRunSpec
	Status KsBuilderRunStatus
}

type KsBuilderStatus struct {
	RunCount     int
	LastRunState string
	LastRunName  string
}

type KsBuilderRunStatus struct {
	StartTime      *metav1.Time
	CompletionTime *metav1.Time
	RunState       string
}

type KsBuilderRunSpec struct {
}

type KsBuilderSpec struct {
	Config pkgapi.Config
}

//
// KsBuilder Functions and Structs
//
// +k8s:deepcopy-gen=false
type KsBuilderStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type KsBuilderStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type KsBuilderList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []KsBuilder
}

func (KsBuilder) NewStatus() interface{} {
	return KsBuilderStatus{}
}

func (pc *KsBuilder) GetStatus() interface{} {
	return pc.Status
}

func (pc *KsBuilder) SetStatus(s interface{}) {
	pc.Status = s.(KsBuilderStatus)
}

func (pc *KsBuilder) GetSpec() interface{} {
	return pc.Spec
}

func (pc *KsBuilder) SetSpec(s interface{}) {
	pc.Spec = s.(KsBuilderSpec)
}

func (pc *KsBuilder) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *KsBuilder) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc KsBuilder) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store KsBuilder.
// +k8s:deepcopy-gen=false
type KsBuilderRegistry interface {
	ListKsBuilders(ctx request.Context, options *internalversion.ListOptions) (*KsBuilderList, error)
	GetKsBuilder(ctx request.Context, id string, options *metav1.GetOptions) (*KsBuilder, error)
	CreateKsBuilder(ctx request.Context, id *KsBuilder) (*KsBuilder, error)
	UpdateKsBuilder(ctx request.Context, id *KsBuilder) (*KsBuilder, error)
	DeleteKsBuilder(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewKsBuilderRegistry(sp builders.StandardStorageProvider) KsBuilderRegistry {
	return &storageKsBuilder{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageKsBuilder struct {
	builders.StandardStorageProvider
}

func (s *storageKsBuilder) ListKsBuilders(ctx request.Context, options *internalversion.ListOptions) (*KsBuilderList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*KsBuilderList), err
}

func (s *storageKsBuilder) GetKsBuilder(ctx request.Context, id string, options *metav1.GetOptions) (*KsBuilder, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*KsBuilder), nil
}

func (s *storageKsBuilder) CreateKsBuilder(ctx request.Context, object *KsBuilder) (*KsBuilder, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*KsBuilder), nil
}

func (s *storageKsBuilder) UpdateKsBuilder(ctx request.Context, object *KsBuilder) (*KsBuilder, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*KsBuilder), nil
}

func (s *storageKsBuilder) DeleteKsBuilder(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}

//
// KsBuilderRun Functions and Structs
//
// +k8s:deepcopy-gen=false
type KsBuilderRunStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type KsBuilderRunStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type KsBuilderRunList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []KsBuilderRun
}

func (KsBuilderRun) NewStatus() interface{} {
	return KsBuilderRunStatus{}
}

func (pc *KsBuilderRun) GetStatus() interface{} {
	return pc.Status
}

func (pc *KsBuilderRun) SetStatus(s interface{}) {
	pc.Status = s.(KsBuilderRunStatus)
}

func (pc *KsBuilderRun) GetSpec() interface{} {
	return pc.Spec
}

func (pc *KsBuilderRun) SetSpec(s interface{}) {
	pc.Spec = s.(KsBuilderRunSpec)
}

func (pc *KsBuilderRun) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *KsBuilderRun) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc KsBuilderRun) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store KsBuilderRun.
// +k8s:deepcopy-gen=false
type KsBuilderRunRegistry interface {
	ListKsBuilderRuns(ctx request.Context, options *internalversion.ListOptions) (*KsBuilderRunList, error)
	GetKsBuilderRun(ctx request.Context, id string, options *metav1.GetOptions) (*KsBuilderRun, error)
	CreateKsBuilderRun(ctx request.Context, id *KsBuilderRun) (*KsBuilderRun, error)
	UpdateKsBuilderRun(ctx request.Context, id *KsBuilderRun) (*KsBuilderRun, error)
	DeleteKsBuilderRun(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewKsBuilderRunRegistry(sp builders.StandardStorageProvider) KsBuilderRunRegistry {
	return &storageKsBuilderRun{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageKsBuilderRun struct {
	builders.StandardStorageProvider
}

func (s *storageKsBuilderRun) ListKsBuilderRuns(ctx request.Context, options *internalversion.ListOptions) (*KsBuilderRunList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*KsBuilderRunList), err
}

func (s *storageKsBuilderRun) GetKsBuilderRun(ctx request.Context, id string, options *metav1.GetOptions) (*KsBuilderRun, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*KsBuilderRun), nil
}

func (s *storageKsBuilderRun) CreateKsBuilderRun(ctx request.Context, object *KsBuilderRun) (*KsBuilderRun, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*KsBuilderRun), nil
}

func (s *storageKsBuilderRun) UpdateKsBuilderRun(ctx request.Context, object *KsBuilderRun) (*KsBuilderRun, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*KsBuilderRun), nil
}

func (s *storageKsBuilderRun) DeleteKsBuilderRun(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
